### ISSUE TITLE
Gitnesse Crashes When Gherkin Syntax Indicator Is Capitalized

### ISSUE THREAD

**Issue by nomadicoder** [hybridgroup/gitnesse#12]
Run gitnesse on a git-wiki entry in which the syntax indicator for gherkin is capitalized results.
Gherkin generates error with trace dump.

Example:

``````
```Gherkin
Feature: Addition

  As a user
  I want add two numbers
  So that I can pass my math test

  Background:
    Given a is "1"
    And b is "1"
    When I add a to b
    Then I should see "2"
```
``````

Results in:

```
undefined method `[]' for nil:NilClass (NoMethodError)
[Dump follows]
```

**Comment by stewart** [comment]
Closing this issue, was patched as part of rewrite and no longer present in latest version of Gitnesse.
