### ISSUE TITLE
Gitnesse Crashes Pushing or Pulling Empty Gherkin Tag

### ISSUE THREAD

**Issue by nomadicoder** [hybridgroup/gitnesse#13]
Create a feature in the wiki page

``````
```gherkin
```
``````

Execute 

```
gitnesse
```

Generates the error:

```
"wiki.rb:54:in `[]': no implicit conversion from nil to integer (TypeError)"
```

Secondary problem:
The output does not indicate which page is in error. We see the last file processed as "updated" or "didn't change", but no indication that the problem was in the empty feature page.

**Comment by stewart** [comment]
Closing this issue, as the bug has been addressed in the gitnesse rewrite and is no longer present in the latest release.
