### ISSUE TITLE
First-line tags not pulled

### ISSUE THREAD

**Issue by ess** [hybridgroup/gitnesse#16]
Given the following feature stored in a wiki:

``` gherkin
@sometag
Feature: Some feature
  Scenario: Some scenario
    Given the state of things
    When I do this one thing
    Then another thing will happen
```

Pulling the feature omits the leading tag from the file output.

**Comment by stewart** [comment]
Closing this issue, as it was fixed as part of patch for #17 and in latest release of Gitnesse.
