### ISSUE TITLE
Renaming git feature does not reflect on the wiki

### ISSUE THREAD

**Issue by chischaschos** [hybridgroup/gitnesse#19]
I had a feature let's call it feature/x.feature, I _git mv_ it to feature/y.feature. The wiki ended up having to features instead of just the y.feature one. Is this expected behaviour?

**Comment by stewart** [comment]
Sorry I didn't get to this earlier! Yes, this is a bug in the existing release of Gitnesse, and has been addressed as part of the rewrite. Our current strategy when pushing features to the wiki
- Clone wiki
- `git rm` all feature files
- Add all local features to wiki, `git add`-ing them as you do
- `git commit && git push`

This means that if features are no longer in the local `features/` dir, they will be removed from the wiki on `gitnesse push`. Does this provide the behaviour you're expecting?

**Comment by deadprogram** [comment]
+1

**Comment by stewart** [comment]
Closing this issue, as the functionality is now present in the latest release of Gitnesse.
