### ISSUE TITLE
Scenario outlines break gitnesse run

### ISSUE THREAD

**Issue by jondkinney** [hybridgroup/gitnesse#21]
I've tried twice now to run 'gitnesse run' to annotate my feature files, but unfortunately it's hanging for this scenario outline:

![screen shot 2013-10-02 at 12 03 53 pm](https://f.cloud.github.com/assets/4521/1255413/d8c5a342-2b84-11e3-957a-79e39eb6bc7e.png)

The nested feature support works great though! Thanks!

Let me know if you can't reproduce this scenario outline issue and I may be able to help troubleshoot.

**Comment by jondkinney** [comment]
OH, I had to do ctrl-c to break out of `gitnesse run` to get that stack trace. Memory was ballooning at about 100mb every second when I let it run.

Thanks again!

**Comment by stewart** [comment]
Sorry for not getting to this earlier! GitHub is terrible at letting me know when issues have been opened. Can you provide the feature file that's causing the error so I can do some ad-hoc testing to figure out the problem?

**Comment by jondkinney** [comment]
Below is the feature file contents. The file is located at: `features/issuer/00_creating_a_new_company.feature`

``` gherkin
Feature: creating a new company
  In order to have many campaigns
  As an issuer
  I want to create a company to which my campaigns can belong

Background:
  Given I am logged in as an entrepreneur
  And I have agreed to the terms of the crowdfunding platform

  Scenario: prompting for creation of a new company before starting the first campaign
    Given I am on the campaign dashboard
    When I follow "Add New Campaign"
    Then I should see "Please add a company before creating a campaign"

  Scenario: creating a new company
    Given I am on the new company page
    When I fill in the company form
    And I press "Create Company"
    Then I should see "Your company was successfully created."
    And I should see "Campaign Guidelines"

  Scenario Outline: creating a new company with an invalid EIN number specified
    Given I am on the new company page
    When I fill in "<field>" with "<value>"
    And I press "Create Company"
    Then I should see "Some errors prevented your company from being saved"
    And I should see "<text>"
  Examples:
    | field | value      | text                                                         |
    | EIN   | 12-3456789 | EIN is the wrong length (should be 9 numbers)                |
    | EIN   | 12345678y  | EIN format is invalid. Ensure there are no dashes or spaces. |

  Scenario: creating a new company with an EIN number that has invalid chars (a letter)
    And I am on the new company page
    When I fill in "EIN" with "12345678y"
    And I press "Create Company"
    And I should see "EIN format is invalid. Ensure there are no dashes or spaces."

  Scenario: Edit company
    Given I have created a company
    And I am on that company's edit page
    And I fill in the company form
    When I press "Update Company"
    Then I should see "Company was successfully updated."
```

Thanks for taking a look!

**Comment by stewart** [comment]
I'm unable to replicate this. `run_features` is a [fairly simple method](https://github.com/hybridgroup/gitnesse/blob/master/lib/gitnesse/cli/task/run.rb#L68-L77), it basically just runs cucumber on your project. Does a normal `cucumber` work?

It might also be possible that `run_features` is not properly loading your app's environment when running `cucumber` because it's not prefixing it with 'bundle exec'.

**Comment by jondkinney** [comment]
Hi @stewart, thanks for getting back to me! All the cukes pass when run outside of `gitness run`. As a test, I commented out that scenario outline and did `gitnesse run` and it successfully completed. When I put that scenario outline back in... then it hung on execution again and I had to ctrl-c to break out. The same stack trace as I posted in the screenshot above showed up.

For now, I broke the scenario outline out into two separate scenarios and those worked through `gitnesse run` just fine (so I'm relatively confident it's not the underlying code or step definitions causing the issue).

If you have any suggestions for how either of us could troubleshoot this further I'd be all ears!

Thanks.

**Comment by stewart** [comment]
I'd like to put up a branch with a small change for you to try later. I think that `gitnesse run` might not be calling the correct version of cucumber.

**Comment by jondkinney** [comment]
@stewart sounds good. Just let me know when it's ready. Thanks for helping troubleshoot!

**Comment by stewart** [comment]
I've pushed the relevant stuff to the `gitnesse-run-improvements` branch, if you'd like to give that a shot for this issue and #24. This [runs `gitnesse run` through Bundler`](https://github.com/hybridgroup/gitnesse/commit/7752730748280a07275b5e0c6a4fcc8e450269d9) and [passes all CLI flags to Cucumber](https://github.com/hybridgroup/gitnesse/commit/08deb32f0cbbcb2556a526a18d6669eb0028bbec).

**Comment by jondkinney** [comment]
I wonder if manually specifying `bundle exec` will hurt people who generate binstubs? Some discussion on binstubs for spring, an application preloader that might make it into rails, here: https://github.com/jonleighton/spring. Binstubs can also be generated by bundler, though that can break some spring stuff as noted in the spring readme. Just throwing that out there as a possible caution! I'll give this a try now.

**Comment by stewart** [comment]
I'm not super-familiar with how binstubs work, but I'm under the impression they're just a way to bypass having to prefix every gem command with `bundle exec`. So the binstub `./bin/rspec` and `bundle exec rspec` load the same version.

**Comment by stewart** [comment]
Latest push to `gitnesse-run-improvements` should handle the issue with your `Scenario Outline` features, can you give it a shot and let me know?

**Comment by jondkinney** [comment]
@stewart the latest changes fixed it right up, thanks!

Now I'm just being picky... but I wonder if you could indent the scenario outline formatting so it doesn't overflow?

Here's how it turned out:

![screen shot 2013-10-09 at 7 52 03 pm](https://f.cloud.github.com/assets/4521/1303066/558d2d3e-3146-11e3-89a5-9eaec9cd2e15.png)

Would you be able to make the scenario outline title be the main title, then have the specific scenario below it prefixed with that same dash? Something like:

`passing` **creating a new company with an invalid EIN number specified**
- _EIN, 12-3456789, EIN is the wrong length (should be 9 numbers)_

Jon's Work Laptop - Oct 09, 2013, 7:50 PM

**Comment by stewart** [comment]
Something like this? 

![screen shot 2013-10-09 at 7 26 10 pm](https://f.cloud.github.com/assets/489142/1303381/5fae16fe-3153-11e3-9d9c-ebc22550b03e.png)

**Comment by jondkinney** [comment]
Yep! I think that works.

![screen shot 2013-10-09 at 11 59 16 pm](https://f.cloud.github.com/assets/4521/1303785/c810a53a-3168-11e3-854e-33bf7fddaa52.png)
