### ISSUE TITLE
Allow a single feature to be run through `gitnesse run`

### ISSUE THREAD

**Issue by jondkinney** [hybridgroup/gitnesse#24]
It'd be great if gitnesse allowed the same options as cucumber as far as control over what file should be run (maybe even the line number of that file too).

My use-case would be working on a single feature and wanting to push the annotated result of that feature's pass/fail status to the wiki without having to run our full 5 min suite.

We use a gitnesse backed wiki as acceptance criteria for stake holders to verify features in a staging environment. Shortening that feedback / collaboration cycle would be a big help!

Thanks again for this awesome tool!

**Comment by stewart** [comment]
I'll be looking into passing arguments through Gitnesse to Cucumber later this morning, I don't think `gitnesse run` allows for arguments, so this should hopefully be fairly simple to implement.

**Comment by jondkinney** [comment]
I was able to run a single feature successfully with the `gitnesse-run-improvements` branch using:

`gitnesse run features/issuer/00_creating_a_new_company.feature`

However, when I reverted to the scenario outline format I got this error: https://gist.github.com/jondkinney/1d981890140854e55121

**Comment by stewart** [comment]
Ah, I think I see what's happening here. Gitnesse's post-scenario hooks don't seem to agree with Cucumber's `Scenario Outline` syntax. I'll look into this. Thanks again.

**Comment by stewart** [comment]
Closing this issue, since it was addressed by https://github.com/hybridgroup/gitnesse/commit/08deb32f0cbbcb2556a526a18d6669eb0028bbec.
