### ISSUE TITLE
private method `project_dir' called for Gitnesse::DirManager:Class

### ISSUE THREAD

**Issue by ess** [hybridgroup/gitnesse#27]
Introduced in f540813b

If DirManager.project_dir is private, the following break:
- lib/gitnesse/hooks.rb
- lib/gitnesse/cli/helpers/wiki_helpers.rb

**Comment by stewart** [comment]
Addressed by https://github.com/hybridgroup/gitnesse/commit/5064bc6cf8bc1436f520a35726f6fa8a504b937a, closing issue.
