### ISSUE TITLE
Gitnesse own tests are not written in gitnesse

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [hybridgroup/gitnesse#9]
They should. It would be [more convincing](http://en.wikipedia.org/wiki/Eating_your_own_dog_food).

**Comment by aratak** [comment]
Eat your own :shit:, guys ;)

**Comment by deadprogram** [comment]
Thanks for the comments. However, you do not "write tests in gitnesse". Gitnesse is not a test framework of its own, it lets you store your Cucumber features in a git-based wiki. 

The unit tests for Gitnesse's own code are all minitest. I'm sure that some acceptance tests could also be written using Cucumber, and added to the project. Pull request?

**Comment by deadprogram** [comment]
This is example of what we think was meant by the original comment:

https://github.com/hybridgroup/gitnesse/wiki/sync_wiki_features_to_code

Right idea? I think we should cover the rest of things like this... @stewart your opinion?

**Comment by stewart** [comment]
Gitnesse currently stores and updates it's own features in a git wiki using gitnesse, so closing this issue.
